#!/bin/sh

# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# /etc/X11/xinit/xinitrc

# if [ -n "$(which luarocks 2>/dev/null)" ]; then
# 	eval $(luarocks path --bin)
# fi

# setxkbmap -option grp:alt_shift_toggle -layout us,ru &

# индикатор и переключатель раскладки клавиатуры для X11.
# gxkb &

# sxhkd & # -c $HOME/.config/sxhkd/sxhkdrc

# systemctl --user import-environment DISPLAY &

# greenclip daemon &

exec awesome
# exex herbstluftwm
